### ISSUE TITLE
withdraw recieve

### ISSUE THREAD

**Issue by notlongfen** [4xmen/Get-Github-Achievements#100]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when i found some bugs in ... 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by notlongfen** [comment]
gg

**Comment by YasinDehfuli** [comment]
You need To close your Issue before 5 minutes to get quickdraw achievement
