### ISSUE TITLE
QuickDraw Achievement Test

### ISSUE THREAD

**Issue by SiwanadSingtong** [4xmen/Get-Github-Achievements#185]
Describe the bug

To Reproduce

Go to 'issue'
Click on 'submit new issue'
Send bug issue to us https://github.com/4xmen/Get-Github-Achievements/issues/new
Expected behavior

Screenshots

Additional context
If you found any other issues. You can send your bug

**Comment by SiwanadSingtong** [comment]
Finish

**Comment by YasinDehfuli** [comment]
You need to close your issue before 5 minutes to get quickdraw achievement. try with another issue or pull request
