### ISSUE TITLE
Useful

### ISSUE THREAD

**Issue by Arsh4am** [4xmen/Get-Github-Achievements#201]
Always useful and informative yet so simple 🤟

**Comment by Arsh4am** [comment]
Helpful tips

**Comment by YasinDehfuli** [comment]
Thanks, dear @Arsh4am, I'm happy to hear it is useful for you.

**Comment by Arsh4am** [comment]
@YasinDehfuli As a person who studied business management who works in the most non-related field x.stack team woke the passion for learning again ✌️👨‍💻

**Comment by YasinDehfuli** [comment]
We are so happy to hear that dear @Arsh4am.
