### ISSUE TITLE
Created a repo that provides Pair Extraordinaire Achievement automatically. 

### ISSUE THREAD

**Issue by Prakash4844** [4xmen/Get-Github-Achievements#58]
Here's the repo: https://github.com/Prakash4844/Get-Pair-Extraordinaire

Check it out, you can create a issue there to get the achievement and help me test it out.

**Comment by YasinDehfuli** [comment]
sorry, i have the badge right now and, you can use github desktop to add contributer, and no need to get email address with this way

**Comment by Prakash4844** [comment]
Actually, I created this for beginner. so they can get the achievement easily.
