### ISSUE TITLE
Very simple typo in "about" section; word "translate" misspelled as "tanslate" in English "about" section

### ISSUE THREAD

**Issue by DouglasKrouth** [4xmen/Get-Github-Achievements#87]
**Describe the bug**
English "about" section contains a typo. Change the word "tanslate" to "translate"

**To Reproduce**
1. Accessible immediately when viewing repo's "about" section

**Expected behavior**
Change the word "tanslate" to "translate"

**Screenshots**
![image](https://github.com/4xmen/Get-Github-Achievements/assets/48629993/dea0bab6-f6a8-4f32-b120-0c536f9d7eb8)

**Additional context**
N/A

**Comment by YasinDehfuli** [comment]
Thanks for report this word mistake. Now you can see the word mistake is fixed

**Comment by DouglasKrouth** [comment]
Awesome!
