### ISSUE TITLE
Quickdraw

### ISSUE THREAD

**Issue by AmineBenzaazaa** [4xmen/Get-Github-Achievements#94]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when i found some bugs in ... 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AmineBenzaazaa** [comment]
Quickdraw

**Comment by AbrnYa** [comment]
Hello @AmineBenzaazaa :
The current tutorials are all sourced from GitHub or the internet. If you are patient, all achievements will be very easy to obtain, and all tutorials are step-by-step hands-on teaching you how to obtain them. If you have better suggestions, you can provide feedback.

Wishing you success soon!🥇

**Comment by YasinDehfuli** [comment]
Dear @AmineBenzaazaa, if you want to get Quickdraw achievement you need to close your issue or Pull request before 5 minutes. Good Luck
